#!/usr/bin/env bash
# Load the portable machine profile. This file is designed to be sourced.
# Precedence:
#   1) explicitly exported ZHIHANG_PROFILE_FILE
#   2) machine_profile.env beside this bundle
#   3) ~/.config/zhihang_v6_7_19/machine.env
#
# The profile is a trusted local shell fragment generated by
# configure_portable_machine.py. No project source file is modified here.

_ZH_PROFILE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_ZH_PROFILE_USER="${XDG_CONFIG_HOME:-${HOME}/.config}/zhihang_v6_7_19/machine.env"
_ZH_PROFILE_BUNDLE="${_ZH_PROFILE_ROOT}/machine_profile.env"

if [[ -n "${ZHIHANG_PROFILE_FILE:-}" ]]; then
  _ZH_PROFILE_SELECTED="${ZHIHANG_PROFILE_FILE}"
elif [[ -f "${_ZH_PROFILE_BUNDLE}" ]]; then
  _ZH_PROFILE_SELECTED="${_ZH_PROFILE_BUNDLE}"
elif [[ -f "${_ZH_PROFILE_USER}" ]]; then
  _ZH_PROFILE_SELECTED="${_ZH_PROFILE_USER}"
else
  _ZH_PROFILE_SELECTED=""
fi

if [[ -n "${_ZH_PROFILE_SELECTED}" ]]; then
  if [[ ! -f "${_ZH_PROFILE_SELECTED}" ]]; then
    echo "[ERROR] machine profile not found: ${_ZH_PROFILE_SELECTED}" >&2
    return 41 2>/dev/null || exit 41
  fi
  # shellcheck disable=SC1090
  source "${_ZH_PROFILE_SELECTED}"
  export ZHIHANG_PROFILE_FILE="${_ZH_PROFILE_SELECTED}"
fi

# Core paths
export ZHIHANG_WS="${ZHIHANG_WS:-${HOME}/xtdrone_competition_ws}"
export ZHIHANG_ROS_SETUP="${ZHIHANG_ROS_SETUP:-/opt/ros/noetic/setup.bash}"
export ZHIHANG_OPTIONAL_UNDERLAY="${ZHIHANG_OPTIONAL_UNDERLAY:-${HOME}/catkin_ws/devel/setup.bash}"
export ZHIHANG_MESSAGE_WS_SETUP="${ZHIHANG_MESSAGE_WS_SETUP:-${HOME}/zhihang_ws/devel/setup.bash}"
export ZHIHANG_XTDRONE_ROOT="${ZHIHANG_XTDRONE_ROOT:-${HOME}/XTDrone}"
export ZHIHANG_PX4_ROOT="${ZHIHANG_PX4_ROOT:-${HOME}/PX4_Firmware}"

# PX4 / Gazebo and XTDrone launch components
export ZHIHANG_PX4_ROS_PACKAGE="${ZHIHANG_PX4_ROS_PACKAGE:-px4}"
export ZHIHANG_PX4_LAUNCH_FILE="${ZHIHANG_PX4_LAUNCH_FILE:-auto}"
export ZHIHANG_PX4_LAUNCH_ARGS="${ZHIHANG_PX4_LAUNCH_ARGS:-}"
export ZHIHANG_PX4_ENV_SCRIPT="${ZHIHANG_PX4_ENV_SCRIPT:-}"
export ZHIHANG_GUARD_ROS_PACKAGE="${ZHIHANG_GUARD_ROS_PACKAGE:-zhihang_xtdrone_guard}"
export ZHIHANG_GUARD_LAUNCH_FILE="${ZHIHANG_GUARD_LAUNCH_FILE:-guard_standard_vtol.launch}"

export ZHIHANG_COMMUNICATION_DIR="${ZHIHANG_COMMUNICATION_DIR:-${ZHIHANG_XTDRONE_ROOT}/communication}"
export ZHIHANG_POSE_SCRIPT="${ZHIHANG_POSE_SCRIPT:-${ZHIHANG_XTDRONE_ROOT}/sensing/pose_ground_truth/get_multi_vehcle_local_pose.sh}"
export ZHIHANG_MODEL_STATE_SCRIPT="${ZHIHANG_MODEL_STATE_SCRIPT:-${ZHIHANG_XTDRONE_ROOT}/zhihang2026/model_state.py}"
export ZHIHANG_COMPETITION_DATA_DIR="${ZHIHANG_COMPETITION_DATA_DIR:-${ZHIHANG_XTDRONE_ROOT}/zhihang2026}"

# QGroundControl and terminal backend
export ZHIHANG_QGC_EXECUTABLE="${ZHIHANG_QGC_EXECUTABLE:-${HOME}/software/QGC/QGroundControl(1).AppImage}"
export ZHIHANG_QGC_ARGS="${ZHIHANG_QGC_ARGS:-}"
export ZHIHANG_START_QGC="${ZHIHANG_START_QGC:-1}"
export ZHIHANG_TERMINAL_BACKEND="${ZHIHANG_TERMINAL_BACKEND:-auto}"
export ZHIHANG_TMUX_SESSION="${ZHIHANG_TMUX_SESSION:-zhihang_v6_7_19}"
export ZHIHANG_HEADLESS="${ZHIHANG_HEADLESS:-0}"

# YOLO runtime. Supported values: auto, conda, venv, system, direct.
export ZHIHANG_YOLO_RUNTIME="${ZHIHANG_YOLO_RUNTIME:-auto}"
export ZHIHANG_YOLO_ENV="${ZHIHANG_YOLO_ENV:-yolo26}"
export ZHIHANG_YOLO_VENV="${ZHIHANG_YOLO_VENV:-${HOME}/.venvs/yolo26}"
export ZHIHANG_YOLO_PYTHON="${ZHIHANG_YOLO_PYTHON:-}"
export ZHIHANG_YOLO_MODEL="${ZHIHANG_YOLO_MODEL:-${HOME}/yolo_models/best.pt}"
export ZHIHANG_YOLO_REQUIRE_CUDA="${ZHIHANG_YOLO_REQUIRE_CUDA:-1}"
export ZHIHANG_YOLO_DEVICES="${ZHIHANG_YOLO_DEVICES:-auto,auto,auto}"
export ZHIHANG_YOLO_QUANTIZE="${ZHIHANG_YOLO_QUANTIZE:-16}"
export ZHIHANG_YOLO_ADAPTIVE="${ZHIHANG_YOLO_ADAPTIVE:-1}"
export ZHIHANG_YOLO_ADAPTIVE_SIZES="${ZHIHANG_YOLO_ADAPTIVE_SIZES:-640,512,416}"
export ZHIHANG_YOLO_MINIMUM_FPS="${ZHIHANG_YOLO_MINIMUM_FPS:-10.0}"
export ZHIHANG_YOLO_PERFORMANCE_WINDOW="${ZHIHANG_YOLO_PERFORMANCE_WINDOW:-5.0}"
export ZHIHANG_YOLO_ADAPTIVE_CHECK_INTERVAL="${ZHIHANG_YOLO_ADAPTIVE_CHECK_INTERVAL:-5.0}"
export ZHIHANG_YOLO_WARMUP_ITERATIONS="${ZHIHANG_YOLO_WARMUP_ITERATIONS:-3}"
export ZHIHANG_YOLO_SOCKET_TIMEOUT="${ZHIHANG_YOLO_SOCKET_TIMEOUT:-20.0}"
export ZHIHANG_YOLO_CONFIDENCE="${ZHIHANG_YOLO_CONFIDENCE:-0.25}"
export ZHIHANG_YOLO_IOU="${ZHIHANG_YOLO_IOU:-0.70}"
export ZHIHANG_YOLO_HOSTS="${ZHIHANG_YOLO_HOSTS:-127.0.0.1,127.0.0.1,127.0.0.1}"
export ZHIHANG_YOLO_BIND_HOST="${ZHIHANG_YOLO_BIND_HOST:-127.0.0.1}"
export ZHIHANG_YOLO_PORT_BASE="${ZHIHANG_YOLO_PORT_BASE:-17771}"
export ZHIHANG_YOLO_START_LOCAL_WORKERS="${ZHIHANG_YOLO_START_LOCAL_WORKERS:-1}"

# Mission defaults
export ZHIHANG_DEFAULT_SCENE="${ZHIHANG_DEFAULT_SCENE:-scene_001_adaptive_v6_7_19_formal}"
export ZHIHANG_DEFAULT_SEED="${ZHIHANG_DEFAULT_SEED:--1}"
export ZHIHANG_RECORD_BAG="${ZHIHANG_RECORD_BAG:-0}"
export ZHIHANG_PROFILE_LOADED=1

if [[ "${ZHIHANG_PROFILE_VERBOSE:-0}" == "1" ]]; then
  echo "[PROFILE] file=${ZHIHANG_PROFILE_FILE:-<defaults>}"
  echo "[PROFILE] ws=${ZHIHANG_WS}"
  echo "[PROFILE] xtdrone=${ZHIHANG_XTDRONE_ROOT}"
  echo "[PROFILE] yolo_runtime=${ZHIHANG_YOLO_RUNTIME} env=${ZHIHANG_YOLO_ENV}"
  echo "[PROFILE] yolo_model=${ZHIHANG_YOLO_MODEL}"
fi

unset _ZH_PROFILE_ROOT _ZH_PROFILE_USER _ZH_PROFILE_BUNDLE _ZH_PROFILE_SELECTED
